modLoader = "javafml"
loaderVersion = "[4,)"
license = "Custom"
#issueTrackerURL = ""

[[mods]]
modId = "beachparty"
version = "${version}"
displayName = "[Let's Do] Beachparty"
authors = "Satisfy, BaumeisterJo, Cristelknight"
description = '''
Take a break - build sandcastles, drink cocktails and enjoy your life.
'''
logoFile = "pack.png"

[[dependencies.beachparty]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beachparty]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beachparty]]
modId = "architectury"
type = "required"
versionRange = "[9.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.beachparty]]
modId = "doapi"
type = "required"
versionRange = "[1.3.0,)"
ordering = "AFTER"
side = "BOTH"